

DROP TABLE IF EXISTS TAREFA;
CREATE TABLE TAREFA(
	TAREFA_ID SERIAL PRIMARY KEY NOT NULL,
	TAREFA_DESCRICAO VARCHAR ,
	TAREFA_PRIORIDADE VARCHAR,
	TAREFA_SITUACAO VARCHAR 
);


INSERT INTO TAREFA(TAREFA_DESCRICAO,TAREFA_PRIORIDADE,TAREFA_SITUACAO) VALUES ('Exercicios as 15hs','ALTA','PENDENTE');

SELECT * FROM TAREFA;